### ISSUE TITLE
"if(gainid < 0.01) gainid = 0.01; // clamp" has no effect (line 257)

### ISSUE THREAD

**Issue by preuter** [karpathy/tsnejs#3]
As of today, on line 257 of tsne.js, the line "if(gainid < 0.01) gainid = 0.01; // clamp" has no effect, and the intention of this code is unknown, insofar as I don't know what the algorithm should do here.

Should newgain be clamped? or should gainid be clamped prior to the multiply by 0.8, in line 256?
var gainid goes unused for the rest of the loop.

**Comment by karpathy** [comment]
oops, thanks for bringing this up, I think it's a bug - it should be clamping newgain.

**Comment by preuter** [comment]
Agreed. I was skimming a python t-SNE implementation and indeed the newgain gets the clamp.  I leave this in your hands for the commit.  Thanks for getting back to me so fast!

**Comment by karpathy** [comment]
Great, just pushed it. Thanks!
